---
sudo: false
language: rust
os:
  - linux
  - osx
dist: trusty
osx_image: xcode9.2
rust: stable
env:
  global:
    - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
    - FWOOTHEE_RUBY_VERSION: 2.3.5
    - FWOOTHEE_RUBY_VERSION: 2.4.2
    - FWOOTHEE_RUBY_VERSION: 2.5.0
matrix:
  include:
    - os: linux
      dist: trusty
      env: FWOOTHEE_RUBY_VERSION=2.3.5 RUBY_STATIC=1
    - os: linux
      dist: trusty
      env: FWOOTHEE_RUBY_VERSION=2.4.2 RUBY_STATIC=1
    - os: linux
      dist: trusty
      env: FWOOTHEE_RUBY_VERSION=2.5.0 RUBY_STATIC=1
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.3.5
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.3.5
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.3.5 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.2
      env: FWOOTHEE_RUBY_VERSION=2.3.5 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.3.5 RUBY_STATIC=1
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.4.2
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.4.2
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.4.2 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.2
      env: FWOOTHEE_RUBY_VERSION=2.4.2 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.4.2 RUBY_STATIC=1
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.5.0
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.5.0
    - os: osx
      osx_image: xcode8
      env: FWOOTHEE_RUBY_VERSION=2.5.0 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.2
      env: FWOOTHEE_RUBY_VERSION=2.5.0 RUBY_STATIC=1
    - os: osx
      osx_image: xcode9.3beta
      env: FWOOTHEE_RUBY_VERSION=2.5.0 RUBY_STATIC=1

cache:
  cargo: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor/bundle

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
    fi
    rvm install "$FWOOTHEE_RUBY_VERSION"
    rvm use "$FWOOTHEE_RUBY_VERSION"
    ruby --version
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which bundle > /dev/null; then
      gem install bundler
    fi
  - bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

script:
  - bundle exec rake spec
  - bundle exec rake thermite:tarball
  - bundle exec rake install
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      gem uninstall fast_woothee
      CARGO=fake bundle exec rake install
    fi
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      gem uninstall fast_woothee
      CARGO=fake gem install pkg/*.gem
      bundle exec rake spec
    fi
  - if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi

deploy:
  provider: releases
  api_key:
    secure: 3sPpXpRZ5FzEL3wYaGDD9jSXiPl9SLA4F0GME8JMnN69UyNPmqN5Dy5FHEN0HzQSn+RQ5hxkN3GFJgIZ1v7acJ66cgBJL5SCuol3qCeXg8dEYssOREeM5VFAwb4+y3gUNgD/nNmYJVHKZezVaLE/VOwCQyRj3BDqnlG0bVCzc9yjE81SmjUy9/ABBWRBrlC+tyrwAg+qaZLFg537RrAy4wFngr7xrilvnFxh4M+UCB1o7xzQbGBaunFf7K3+bG9mENBUdsr5fkMIr3HfXilBERpVbGXbMAhseprPQBlbTz1u96uQFuf892hIxQOtJxTAMlvOBOchFjnd/B4mm1oLEwLKJkPBC/hiGwXbM5MvWJxLnH1T6P9Hz9Vv7M3qLv7k3+/sNxnQ048AyH+IAVYXT85QGcRXlNQoQFUs6NBl4MC/izfcfLLcLbt5FBWWWofFguzgrGqJYdLk00QL+V8aQ/5kqwsOjaJTx46fLABBTfRmQTPZWOcJWta/ZCLK+MKpvVPbjInQyh9pLkfQrmjRNyNvdYpI8zGkd25EvUSo5fjLpx0pqHmptiyP6EmuD1PKPPR/lLuDknPZoh9l1kGseYYIzLPd164rfhrgtwSVArUusp/ZV1aUDUufIZGJSwz/AJwnX9h2hEQOQElr0f6PUA3a9MTvS6r+jMasASysm1I=
  file: fast_woothee-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: ${TRAVIS_TAG} =~ '-rust'
    repo: ianks/fast_woothee
    tags: true
