---
version: 2.1

orbs:
  matrix:
    jobs:
      execute:
        parameters:
          ruby_version:
            description: Version of Ruby to use
            type: string
          ruby_static:
            description: Whether to compile a static binary
            type: boolean
          os:
            description: Operating system
            type: string
        executor:
          name: << parameters.os >>
          version: <<parameters.ruby_version >>
        steps:
          - checkout
          - run: |
              if [ -x "$(command -v brew)" ]; then
                curl -sSL https://get.rvm.io | bash
                rvm install <<parameters.ruby_version>>
              fi
          - run: git submodule update --init --recursive
          - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
          - when:
              condition: << parameters.ruby_static >>
              steps:
                - run: echo 'export RUBY_STATIC=1' >> $BASH_ENV
          - run:
              background: true
              command: |
                touch "$THERMITE_DEBUG_FILENAME"
                tail -f "$THERMITE_DEBUG_FILENAME"
          - run: gem update --system
          - run: gem install bundler
          - restore_cache:
              keys:
                - bundler-{{ arch }}-<< parameters.ruby_version >>-{{ checksum "fast_woothee.gemspec" }}
                - bundler-{{ arch }}-<< parameters.ruby_version >>
          - run:
              name: Bundle Install
              command: bundle check || bundle install
          - save_cache:
              key: bundler-{{ arch }}-<< parameters.ruby_version >>-{{ checksum "fast_woothee.gemspec" }}
              paths:
                - vendor/bundle
          - run: bundle exec rake spec
          - run: bundle exec rake thermite:tarball
          - run: bundle exec rake install
    executors:
      osx:
        parameters:
          version:
            type: string
        macos:
          xcode: "9.2"
      linux:
        parameters:
          version:
            type: string
        docker:
          - image: circleci/ruby:<<parameters.version>>
            environment:
              THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
              BUNDLE_JOBS: 3
              BUNDLE_RETRY: 3
              BUNDLE_PATH: vendor/bundle

workflows:
  build-test-deploy:
    jobs:
      - matrix/execute:
          ruby_version: "2.4"
          ruby_static: true
          os: 'linux'
      - matrix/execute:
          ruby_version: "2.4"
          ruby_static: false
          os: 'linux'
      - matrix/execute:
          ruby_version: "2.5"
          ruby_static: true
          os: 'linux'
      - matrix/execute:
          ruby_version: "2.5"
          ruby_static: false
          os: 'linux'
      - matrix/execute:
          ruby_version: "2.6"
          ruby_static: true
          os: 'linux'
      - matrix/execute:
          ruby_version: "2.6"
          ruby_static: false
          os: 'linux'

      - matrix/execute:
          ruby_version: "2.4"
          ruby_static: true
          os: 'osx'
      - matrix/execute:
          ruby_version: "2.4"
          ruby_static: false
          os: 'osx'
      - matrix/execute:
          ruby_version: "2.5"
          ruby_static: true
          os: 'osx'
      - matrix/execute:
          ruby_version: "2.5"
          ruby_static: false
          os: 'osx'
      - matrix/execute:
          ruby_version: "2.6"
          ruby_static: true
          os: 'osx'
      - matrix/execute:
          ruby_version: "2.6"
          ruby_static: false
          os: 'osx'
